local Flux = loadstring(game:HttpGet"https://raw.githubusercontent.com/dawid-scripts/UI-Libs/main/fluxlib.txt")()
Flux:Notification("Press left control to hide the UI!", "OK")
local win = Flux:Window("verifyhub", game:GetService("MarketplaceService"):GetProductInfo(game.PlaceId).Name, Color3.fromRGB(0, 255, 0), Enum.KeyCode.LeftControl)
local tab = win:Tab("Friendly", "http://www.roblox.com/asset/?id=6022668888")
tab:Button("AlexVR", "Executes AlexVR, a fake vr script, controls can be seen inside the chat", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/Alexplayrus2/verifyhub/main/alexvr.lua'))()
end)
tab:Button("Headcrab Hat", "Gives you a headcrab looking hat", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/Alexplayrus2/verifyhub/main/headcraphat.lua'))()
Flux:Notification("You now have a headcrab on your head", "OK")
end)
local tab2 = win:Tab("Annoying", "http://www.roblox.com/asset/?id=6022668888")
tab2:Button("Hold mouse to give penis", "Hold your mouse on someone to give them a long penis!", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/Alexplayrus2/verifyhub/main/penis.lua'))()
Flux:Notification("Hold your mouse over a player to give them a penis, stop holding to remove it (oh no)", "ok lol")
end)
